export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

  SET_ITEM: "SET_ITEM",
  REMOVE_SELECTED_ITEM: "REMOVE_SELECTED_ITEM",

  ADD_AMOUNT_ITEM: "ADD_AMOUNT_ITEM",
  REMOVE_AMOUNT_ITEM: "REMOVE_AMOUNT_ITEM",
  
  SET_AMOUNT: "SET_AMOUNT",
  REMOVE_SELECTED_AMOUNT: "REMOVE_SELECTED_AMOUNT",
  
};
